### ISSUE TITLE
No module named 'EffSeg'

### ISSUE THREAD

**Issue by liaochuanlin** [SCoulY/MuSCLe#4]
Traceback (most recent call last):
  File "/home/lcl/MuSCLe-main/train_mcl.py", line 18, in <module>
    from src.MuSCLe import *
  File "/home/lcl/MuSCLe-main/src/MuSCLe.py", line 6, in <module>
    from src.edge import *
  File "/home/lcl/MuSCLe-main/src/edge.py", line 10, in <module>
    from EffSeg import *
ModuleNotFoundError: No module named 'EffSeg'

**Comment by SCoulY** [comment]
Thanks for showing interest in our work!
The import error has been fixed.
